apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # lables of deployment resource
  labels:
    app: mysql
    tier: mysql
    purpose: expense
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      purpose: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        purpose: expense
    spec:
      containers:
      - name: nginx
        image: balaguru20/mysql:1.0.0